### ISSUE TITLE
list of sequences supported

### ISSUE THREAD

**Issue by KrisThielemans** [ismrmrd/ge_to_ismrmrd#13]
thanks for this project! Is there a list of sequences that are already supported? Would help us with deciding on which acquisitions to try.

**Comment by roopchansinghv** [comment]
Thanks for asking!  As of 2021.01.14 we have support for GE's 2D GRE and FSE pulse sequences - sample P-files and ScanArchives of these ship with the  converter code in the 'sampleData' directory.  We have only tested fully sampled versions of these.  Since use Orchestra's indexing - hopefully it should "just work" for accelerated versions of these PSDs as well.

The big thing missing right now is support for any 3D GRE or FSE kind of pulse sequence.  Happy to accept pull requests if you are willing to share any efforts on these.  They are currently not a pressing area of research for us.

We also have support for GE's EPI sequence.  To use Gadgetron's current algorithms for EPI reconstruction - you would need to add a bit of code to save the EPI ramp times into the ScanArchive.  [My fork](https://github.com/roopchansinghv/ge_to_ismrmrd) of this repository is bit further along in this aspect.

**Comment by roopchansinghv** [comment]
EPI conversion should be supported as of [this](https://github.com/ismrmrd/ge_to_ismrmrd/pull/14) pull request.

The largest "gap" in conversion at this time is for Cartesian 3D sequences.  As always, PRs welcome!  Closing this issue for now.

Thanks!
