### ISSUE TITLE
Errors when converting GE Raw data

### ISSUE THREAD

**Issue by RitiP** [ismrmrd/ge_to_ismrmrd#18]
Hi,

I have been able to successfully create the setup for GE conversion repo following the steps provided [here](https://github.com/ismrmrd/ge_to_ismrmrd/blob/master/README.md). However, for some of the files the converter fails with the following error: 
<img width="1439" alt="Screen Shot 2021-12-31 at 8 28 40 AM" src="https://user-images.githubusercontent.com/43425462/148266727-91347dd7-6bc2-4cf6-8227-8c210d96cdeb.png">

System specifications:
Ubuntu 18.04
Orchestra 2.0
openssl 1.0.0

It's be great if anyone can provide any information regarding what could be a possible cause behind this issue. Thanks in advance!

**Comment by roopchansinghv** [comment]
Hi - I've not come across this error before.  Is this error generated when converting a P-file, or a ScanArchive?  What pulse sequence was used to generate these data?

From what I can trace through Orchestra's header files, if the Legacy::LxControlSource object (as instantiated [here](https://github.com/ismrmrd/ge_to_ismrmrd/blob/3b8ad952092ca980098bd0a382315d38d24b36ce/src/GERawConverter.cpp#L61)) runs into a Baseline acquisition, it will throw an Exception - which is most likely what you are seeing.

If this is a 2D or EPI scan, you can utilize a LxControlSource::DisableBaselineProcessing() function call to allow you to process baseline data, or if you don't need these and would just want to skip them, then you can check if an acquisition is a Baseline acquisition and skip over it.

I've gleaned this information from the header files in Orchestra's $SDKTOP directory - so I don't have access to any more information (from GE or otherwise) than you have available.  You can also run Doxygen over the $SDKTOP/include/recon directory to generate a browsable set of documentation - this is what I've used to develop this converter.

**Comment by RitiP** [comment]
Hi @roopchansinghv ,

Is it possible to share the data with you over a discrete channel?  Also, as far as I know, all of the files are P-files which are a 2D scan created with regular spin echo pulse. However, for most of them it is failing to convert. For a few it was able to read the file but the h5 file created was empty(no data inside it at all). 
Additionally, if you can let me know where exactly I can make the changes you mentioned, that'd be incredibly helpful! I'm a deep learning researcher trying to work with MRI data but converting them has been a great issue for me. Any kind of help is appreciated. Thanks!

**Comment by RitiP** [comment]
Hi @roopchansinghv , 
Can you please guide me where exactly I need to make this change? 

" **If this is a 2D or EPI scan, you can utilize a LxControlSource::DisableBaselineProcessing() function call to allow you to process baseline data, or if you don't need these and would just want to skip them, then you can check if an acquisition is a Baseline acquisition and skip over it.** "
